export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const DELETE_POST_OPTIMISTIC = "DELETE_POST_OPTIMISTIC";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const SORT_BY_TITLE = "SORT_BY_TITLE";
export const SORT_BY_DATE = "SORT_BY_DATE";
export const APPLY_SEARCH_BY_KEYWORD = "APPLY_SEARCH_BY_KEYWORD";
export const PERFORM_SEARCH_BY_KEYWORD = "PERFORM_SEARCH_BY_KEYWORD";