export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
